### PR TITLE
support for syncing session id with JS sdk

### PR DESCRIPTION
**Pull request by parisholley**

### CODE REVIEW

**Comment by jonyo** [comment]
@parisholley What is your use case for adding the session_id?  From the title it sounds like you are syncing users across PHP and JS?  I'm just wondering if what you are trying to accomplish could instead be done using `deviceId` as documented in the readme in the [logging anonymous users](https://github.com/zumba/amplitude-php#logging-anonymous-users) section?

The `session_id` is one of the optional [amplitude specific keys](https://amplitude.zendesk.com/hc/en-us/articles/204771828-HTTP-API#optional-amplitude-specific-keys-for-the-event-argument) that has a special use on the back end in Amplitude.  I can see the argument for exposing all 3 as event properties, since it does not use those internally like the JS SDK does, but only if there is a scenario where using `deviceId` alone will not work.

If we do add this one, we should probably also add the other 2 optional fields, `event_id` and `insert_id` as well.

Also this will need to bump the version to `2.0.0` as this is breaking change:  Before if you used `$event->sessionId` (or `eventId` or `insertId`) it would end up getting set in the `event_properties` and would have no special behavior in Amplitude.  After these changes those would get set directly as event properties, so could potentially break something if you are using that property already in previous version.

**Comment by parisholley** [comment]
@jonyo Semantically, I would say setting the deviceId to sessionId isn't the correct approach and that documentation should be changed if we are thinking of bumping to 2.0. Users exist across sessions, so amplitude will never be able to associate them together under one user if you do not have a consistent device id/user id.

Not sure you gain much value in a service like Amplitude if you are writing backed only events for web. This SDK should likely focus on JS/PHP combination or a pure native mobile end point. 

Also, the Amplitude interface becomes difficult to interpret the activity feed because events fired through PHP and JS will not connect in one stream, even if the device id is the same. Sending session_id is a must.

Probably makes sense to include event_id/insert_id as well.

For context, all my PHP events are tied to a userId so I only care about deviceId when they are annoymous on the website before signing up, then I let amplitude do the merging.

**Comment by jonyo** [comment]
@parisholley 

> Semantically, I would say setting the deviceId to sessionId isn't the correct approach

Sorry if I wasn't clear, I didn't mean to say to set `deviceId` to the `sessionId`, that wouldn't work at all because `sessionId` is the unix timestamp for when the session started, or -1 for server-side events.  The name is a bit of a misnomer, it is not a unique identifier and I believe would not be useful without also tracking either userId or deviceId.

I was asking if the same result could be accomplished setting the `devideId` to the `deviceId` generated and stored by the JS SDK.

If you need to link some anonymous even server-side, you could pass back the deviceId used by the JS SDK on the next server request, and use it for tracking purposes within PHP.

> Users exist across sessions, so amplitude will never be able to associate them together under one user if you do not have a consistent device id/user id.

Yes, sounds like we are saying the same thing then. :)

> Not sure you gain much value in a service like Amplitude if you are writing backed only events for web. This SDK should likely focus on JS/PHP combination or a pure native mobile end point.

The main use case would be deferred actions that happen server side.  Amplitude has revenue tracking capabilities, if some of your billing process happens as part of a cron or a deferred event, you might want to track a payment being successful as part of a back end process so that the revenue tracking in Amplitude is accurate for your users.

That was one of the main reasons we created the library actually :)

> Also, the Amplitude interface becomes difficult to interpret the activity feed because events fired through PHP and JS will not connect in one stream, even if the device id is the same. Sending session_id is a must.

Hmm, we haven't really had that problem.  Just search by the user and it should pull up the stream across both front-end and back-end events.

In fact, as long as the user ID or device ID matches up, according to Amplitude it will link the events into the same session that happened close together:

> From By default, events that occur within 5 minutes (customizable in the SDK) of each other are grouped into the same session

And it documents having -1 set for sessionId (or simply not set), is the documented way for back-end events to be tracked, events that are not associated with a session.  This is according to [Session FAQ](https://amplitude.zendesk.com/hc/en-us/sections/203255938-Sessions)


> For context, all my PHP events are tied to a userId so I only care about deviceId when they are annoymous on the website before signing up, then I let amplitude do the merging.

Make sure you are:
* After login, in JS SDK make sure you are setting the userId for any event.  Let the JS SDK "link up" a device ID to a user once that user is logged in.
* Do not try to set or reset the deviceId in JS SDK, that could cause it to not link properly
* On server side events, using the PHP SDK, always set the userId, or a captured deviceId that comes from the JS SDK.
* Make sure your JS SDK event userId matches to userId used in server side.

We use both front end tracking with the JS SDK, and back end tracking for things like billing, and we haven't had any trouble with user info linking up.  Once you get the userId tracking in events it should just all link up in Amplitude.

**Comment by parisholley** [comment]
@jonyo 

> Hmm, we haven't really had that problem. Just search by the user and it should pull up the stream across both front-end and back-end events.

http://imgur.com/a/oRizG - i suppose by either syncing the session id or device id, you'd solve the problem, but in that screenshot, all the events listed shared the same user id.

> And it documents having -1 set for sessionId (or simply not set), is the documented way for back-end events to be tracked, events that are not associated with a session.

I'm not sure I would interpret that as "documented way for it to be tracked", it is simply the expected behavior if you aren't associating backend events with frontend (ie: cron/batch jobs). i'd imagine if someone walks through the web interface and you wire backend calls between requests, they should share the same session_id. i'd imagine that internally on their end, this "grouping" of requests is just a front-end feature and isn't represented as such in the underlying data warehouse. similar to how they handled [merged users](https://amplitude.zendesk.com/hc/en-us/articles/205752848-Merged-Users-The-Problem-and-Our-Solution), i'd expect any underlying functional like funnels, etc (or anything that relies on session metrics) would be better of not relying on "run-time" merging.

**Comment by jonyo** [comment]
@parisholley 

> I'm not sure I would interpret that as "documented way for it to be tracked"

I was paraphrasing from [this faq](https://amplitude.zendesk.com/hc/en-us/articles/204758738-Why-does-the-Session-ID-read-1-for-some-events-).

I get your point about linking something on the back end directly to a session though, for that purpose we can add it.

I'm fine with adding it with the following changes:

* Also expose the other 2 optional vars as well.
* Update the readme docs to document usage for the vars

**Pull request closed without merging**
